# THIS IS A GENERATED FILE. PLEASE DONT CHANGE IT MANUALLY

# variants for PGP_STATUS
PGP_STATUS_SUCCESS = 0
PGP_STATUS_UNKNOWN_ERROR = -1
PGP_STATUS_NETWORK_POLICY_VIOLATION = -2
PGP_STATUS_IO_ERROR = -3
PGP_STATUS_INVALID_ARGUMENT = -15
PGP_STATUS_INVALID_OPERATION = -4
PGP_STATUS_MALFORMED_PACKET = -5
PGP_STATUS_PACKET_TOO_LARGE = -29
PGP_STATUS_UNSUPPORTED_PACKET_TYPE = -14
PGP_STATUS_UNSUPPORTED_HASH_ALGORITHM = -9
PGP_STATUS_UNSUPPORTED_PUBLICKEY_ALGORITHM = -18
PGP_STATUS_UNSUPPORTED_ELLIPTIC_CURVE = -21
PGP_STATUS_UNSUPPORTED_SYMMETRIC_ALGORITHM = -10
PGP_STATUS_UNSUPPORTED_AEAD_ALGORITHM = -26
PGP_STATUS_UNSUPPORTED_COMPRESSION_ALGORITHM = -28
PGP_STATUS_UNSUPPORTED_SIGNATURE_TYPE = -20
PGP_STATUS_INVALID_PASSWORD = -11
PGP_STATUS_INVALID_SESSION_KEY = -12
PGP_STATUS_MISSING_SESSION_KEY = -27
PGP_STATUS_MALFORMED_CERT = -13
PGP_STATUS_BAD_SIGNATURE = -19
PGP_STATUS_MANIPULATED_MESSAGE = -25
PGP_STATUS_MALFORMED_MESSAGE = -22
PGP_STATUS_INDEX_OUT_OF_RANGE = -23
PGP_STATUS_UNSUPPORTED_CERT = -24
PGP_STATUS_EXPIRED = -30
PGP_STATUS_NOT_YET_LIVE = -31
PGP_STATUS_FORCE_WIDTH = 2147483647

# variants for PGP_ARMOR_KIND
PGP_ARMOR_KIND_ANY = 0
PGP_ARMOR_KIND_MESSAGE = 1
PGP_ARMOR_KIND_PUBLICKEY = 2
PGP_ARMOR_KIND_SECRETKEY = 3
PGP_ARMOR_KIND_SIGNATURE = 4
PGP_ARMOR_KIND_FILE = 5
PGP_ARMOR_KIND_FORCE_WIDTH = 2147483647

# variants for PGP_REVOCATION_STATUS
PGP_REVOCATION_STATUS_REVOKED = 0
PGP_REVOCATION_STATUS_COULD_BE = 1
PGP_REVOCATION_STATUS_NOT_AS_FAR_AS_WE_KNOW = 2
PGP_REVOCATION_STATUS_FORCE_WIDTH = 2147483647

# variants for PGP_REASON_FOR_REVOCATION
PGP_REASON_FOR_REVOCATION_UNSPECIFIED = 0
PGP_REASON_FOR_REVOCATION_KEY_SUPERSEDED = 1
PGP_REASON_FOR_REVOCATION_KEY_COMPROMISED = 2
PGP_REASON_FOR_REVOCATION_KEY_RETIRED = 3
PGP_REASON_FOR_REVOCATION_UID_RETIRED = 4
PGP_REASON_FOR_REVOCATION_FORCE_WIDTH = 2147483647

# variants for PGP_PUBLIC_KEY_ALGO
PGP_PUBLIC_KEY_ALGO_RSA_ENCRYPT_SIGN = 0
PGP_PUBLIC_KEY_ALGO_RSA_ENCRYPT = 1
PGP_PUBLIC_KEY_ALGO_RSA_SIGN = 2
PGP_PUBLIC_KEY_ALGO_ELGAMAL_ENCRYPT = 3
PGP_PUBLIC_KEY_ALGO_DSA = 4
PGP_PUBLIC_KEY_ALGO_ECDH = 5
PGP_PUBLIC_KEY_ALGO_ECDSA = 6
PGP_PUBLIC_KEY_ALGO_ELGAMAL_ENCRYPT_SIGN = 7
PGP_PUBLIC_KEY_ALGO_EDDSA = 8
PGP_PUBLIC_KEY_ALGO_FORCE_WIDTH = 2147483647

# variants for PGP_TAG
PGP_TAG_RESERVED0 = 0
PGP_TAG_PKESK = 1
PGP_TAG_SIGNATURE = 2
PGP_TAG_SKESK = 3
PGP_TAG_ONE_PASS_SIG = 4
PGP_TAG_SECRET_KEY = 5
PGP_TAG_PUBLIC_KEY = 6
PGP_TAG_SECRET_SUBKEY = 7
PGP_TAG_COMPRESSED_DATA = 8
PGP_TAG_SED = 9
PGP_TAG_MARKER = 10
PGP_TAG_LITERAL = 11
PGP_TAG_TRUST = 12
PGP_TAG_USER_ID = 13
PGP_TAG_PUBLIC_SUBKEY = 14
PGP_TAG_UNASSIGNED15 = 15
PGP_TAG_UNASSIGNED16 = 16
PGP_TAG_USER_ATTRIBUTE = 17
PGP_TAG_SEIP = 18
PGP_TAG_MDC = 19
PGP_TAG_UNASSIGNED20 = 20
PGP_TAG_UNASSIGNED21 = 21
PGP_TAG_UNASSIGNED22 = 22
PGP_TAG_UNASSIGNED23 = 23
PGP_TAG_UNASSIGNED24 = 24
PGP_TAG_UNASSIGNED25 = 25
PGP_TAG_UNASSIGNED26 = 26
PGP_TAG_UNASSIGNED27 = 27
PGP_TAG_UNASSIGNED28 = 28
PGP_TAG_UNASSIGNED29 = 29
PGP_TAG_UNASSIGNED30 = 30
PGP_TAG_UNASSIGNED31 = 31
PGP_TAG_UNASSIGNED32 = 32
PGP_TAG_UNASSIGNED33 = 33
PGP_TAG_UNASSIGNED34 = 34
PGP_TAG_UNASSIGNED35 = 35
PGP_TAG_UNASSIGNED36 = 36
PGP_TAG_UNASSIGNED37 = 37
PGP_TAG_UNASSIGNED38 = 38
PGP_TAG_UNASSIGNED39 = 39
PGP_TAG_UNASSIGNED40 = 40
PGP_TAG_UNASSIGNED41 = 41
PGP_TAG_UNASSIGNED42 = 42
PGP_TAG_UNASSIGNED43 = 43
PGP_TAG_UNASSIGNED44 = 44
PGP_TAG_UNASSIGNED45 = 45
PGP_TAG_UNASSIGNED46 = 46
PGP_TAG_UNASSIGNED47 = 47
PGP_TAG_UNASSIGNED48 = 48
PGP_TAG_UNASSIGNED49 = 49
PGP_TAG_UNASSIGNED50 = 50
PGP_TAG_UNASSIGNED51 = 51
PGP_TAG_UNASSIGNED52 = 52
PGP_TAG_UNASSIGNED53 = 53
PGP_TAG_UNASSIGNED54 = 54
PGP_TAG_UNASSIGNED55 = 55
PGP_TAG_UNASSIGNED56 = 56
PGP_TAG_UNASSIGNED57 = 57
PGP_TAG_UNASSIGNED58 = 58
PGP_TAG_UNASSIGNED59 = 59
PGP_TAG_PRIVATE0 = 60
PGP_TAG_PRIVATE1 = 61
PGP_TAG_PRIVATE2 = 62
PGP_TAG_PRIVATE3 = 63
PGP_TAG_FORCE_WIDTH = 2147483647

# variants for PGP_CERT_CIPHER
PGP_CERT_CIPHER_SUITE_CV25519 = 0
PGP_CERT_CIPHER_SUITE_RSA3K = 1
PGP_CERT_CIPHER_SUITE_P256 = 2
PGP_CERT_CIPHER_SUITE_P384 = 3
PGP_CERT_CIPHER_SUITE_P521 = 4
PGP_CERT_CIPHER_SUITE_RSA2K = 5
PGP_CERT_CIPHER_SUITE_RSA4K = 6
PGP_CERT_CIPHER_SUITE_FORCE_WIDTH = 2147483647

# variants for PGP_MESSAGE_LAYER
PGP_MESSAGE_LAYER_COMPRESSION = 1
PGP_MESSAGE_LAYER_ENCRYPTION = 2
PGP_MESSAGE_LAYER_SIGNATURE_GROUP = 3
PGP_MESSAGE_LAYER_CODE_FORCE_WIDTH = 2147483647

# variants for PGP_VERIFICATION_RESULT
PGP_VERIFICATION_RESULT_GOOD_CHECKSUM = 0
PGP_VERIFICATION_RESULT_MALFORMED_SIGNATURE = 1
PGP_VERIFICATION_RESULT_MISSING_KEY = 2
PGP_VERIFICATION_RESULT_UNBOUND_KEY = 3
PGP_VERIFICATION_RESULT_BAD_KEY = 4
PGP_VERIFICATION_RESULT_BAD_SIGNATURE = 5
PGP_VERIFICATION_RESULT_CODE_FORCE_WIDTH = 2147483647
